[tool.black]
line-length = 80
skip-string-normalization = false

[tool.ruff]
line-length = 80
extend-exclude = [".venv", "dist", "build"]

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
